<a href="https://colab.research.google.com/github/TommySnyd/ds2002-fa26/blob/main/notebooks/01-foundations/2026-09-04%20%E2%80%94%20Submission%20Drill%20and%20Fix%20a%20Broken%20Notebook%20%E2%80%94%20Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DS2002 · Submission Drill and Fix a Broken Notebook

**Lab — 2026-09-04 · Fall 2026**  

---

## Lab 02 — Submission Drill and Fix a Broken Notebook

You have inherited a notebook that does not run. This is the most common way you will meet other people's code, so it is worth practicing deliberately.

Seven cells below are broken. Five throw an error, and two return a wrong answer without complaining at all — those are the dangerous ones. Fix all seven, prove your fixes with assertions, then push through the full submit loop.

**Submit in Canvas:** repository link and notebook link.

### How to read an error before you fix it

Python's traceback is read **bottom up**. The last line names the exception and the problem; the line above it points at your code.

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
    print(greeting)
NameError: name 'greeting' is not defined
```

Four exceptions cover most of what you will hit this semester:

| Exception | Usually means |
|---|---|
| `NameError` | The variable was never created, or the cell that created it never ran |
| `TypeError` | You mixed types — text where a number belongs is the classic |
| `KeyError` | That column or dictionary key does not exist. Check spelling and case |
| `FileNotFoundError` | The path is wrong for *this* environment |

For each fix below, write one sentence in the markdown cell saying what was actually wrong. "It works now" is not a diagnosis.

### Bug 1 — a name that does not exist

In [14]:
# TODO: fix so this prints a greeting - done
#Problem: The name greeting had no value assigned to it, therefore nothing was called when it was printed
#Fix: added a value to the greeting name
greeting = "Hello how's it going?"

print(greeting)

Hello how's it going?

**What was wrong:** The name greeting had no value assigned to it, therefore nothing was called when it was asked to print

### Bug 2 — text where a number belongs

This should print `30`. Note that `'10' + 20` and `'10' + '20'` fail in different ways — make sure you know which one you are looking at.

In [15]:
# TODO: fix so total is the number 30 - done
# Problem is that the number 10 was type(str), and since it was a string value and not a number/integer, the addition could not be performed
# Fix: Remove quotations around the number 10 so that both numbers are integers and can be added
total = 10 + 20
print(total)

30

**What was wrong**: The number 10 was type(str), and since it was a string value and not a number/integer, the addition could not be performed (I didn't know these boxes were edited that's why I have the problem in the to-do section too)

### Bug 3 — off the end of a list

In [16]:
items = ['burger', 'poncho', 'hat']

# TODO: print the LAST item, and do it in a way that still works
#       if someone adds a fourth item tomorrow - done
# Problem: Using the index number 3 calls the 4th value in a list as the funtion starts counting at 0 and not 1
# also using the number 2 doesn't work because it would not consistently print the final number in the set
# Fix: Using -1 calls the last value in each set
print(items[-1])

hat

**What was wrong**: Using the index number 3 calls the 4th value in a list as the funtion starts counting at 0 and not 1. Also using the number 2 doesn't work because it would not consistently print the final number in the set

### Bug 4 — no error, wrong answer

This is supposed to be the average. It prints a number, and the number is wrong.

In [17]:
nums = [2, 4, 6, 8]
# Problem: The formula is wrong, should be divided by 4 or however long the list ends up
# Fix: Keep the first part of the average function but have it divided by the total number of values in the list using len function
average = sum(nums) / len(nums)
print('average:', average)

average: 5.0

**What was wrong**: The formula is wrong, should be divided by 4 or however long the list ends up (len(nums))

### Bug 5 — a table that cannot exist

In [18]:
import pandas as pd
# What was wrong? The data frame arrays were different lengths. You can not call a data frame that has different lengthed arrays
# Fix: Add and additional 'item' value or remove a 'price' value so they're the same
df = pd.DataFrame({'item': ['a', 'b'], 'price': [1, 2]})
print(df)

  item  price
0    a      1
1    b      2

**What was wrong:** The data frame arrays were different lengths. You can not call a data frame that has different lengthed arrays

### Bug 6 — the answer changes when you re-run it

Run the next cell three times and watch the total move. Then fix it using what you built Wednesday: leave the source data alone and derive a new column from it. Your fix must give the same total on every run.

In [19]:
sales = pd.DataFrame({
    'game': ['NC State', 'Louisville'],
    'units': [1450, 1610],
})

# TODO: rewrite these two lines so re-running cannot change the answer
# Problem: The value was compounding and continuing to grow, just like the weekly check in
# fix: By creating a new value and assigning each individual total to be multiplied by the fee *by itself* rather than compouding, you get the same total every time
fee = 1.05
work = sales.copy()
work['Units_after_fee'] = work['units']*fee
#sales['units'] = sales['units'] * 1.05
print('total with fee:', round(work['Units_after_fee'].sum(), 2))

total with fee: 3213.0

In [20]:
# Proof — this must print the same number three times
for _ in range(3):
  work = sales.copy()
  work['Units_after_fee'] = work['units']*fee
    # TODO: rebuild from the raw values and print your total - done, copied the function from above and got the same value printed 3 times
  print('total with fee:', round(work['Units_after_fee'].sum(), 2))
  pass

total with fee: 3213.0
total with fee: 3213.0
total with fee: 3213.0

**What was wrong:** The value was compounding and continuing to grow, just like the weekly check in

### Bug 7 — a path from someone else's laptop

This notebook was written on a machine you do not have. Fix it with the pattern from Wednesday's studio: look for the file, and fall back to the inline sample so the notebook still runs for whoever opens it next.

In [21]:
import os
from io import StringIO

SAMPLE = '''game,units\nNC State,1450\nLouisville,1610\n'''

# TODO: replace this with a lookup + fallback that works anywhere - done: created the path to get to the current working directory
# had to move the SAMPLE into the actual function
# orders = pd.read_csv('/Users/someone/Desktop/gameday_orders.csv')
from io import StringIO

SAMPLE = '''game,units\nNC State,1450\nLouisville,1610\n'''

def load_csv(filename, sample=SAMPLE):
    path = os.path.join((os.getcwd()), filename)
     # TODO: if the file exists, read it and print that you used the real file. - done
    #       otherwise read the sample string and print that you fell back. - done
    # used if else function and os to check if the path exists and if it did exist, to return the path and file and if it did not exist, print the statement from the weekly check-in
    if os.path.exists(path):
      print('Loaded real file', path)
      return pd.read_csv(path)
    else:
      print('File not found, using inline sample:', path)
      return pd.read_csv(StringIO(sample))

orders = load_csv('gameday_orders.csv')
#orders = pd.read_csv('/Users/someone/Desktop/gameday_orders.csv')
orders

File not found, using inline sample: /content/gameday_orders.csv

         game  units
0    NC State   1450
1  Louisville   1610

**What was wrong:** When trying to use the exact function from the weekly check in, I was running into lots if errors even after changing the file. I tried to have the first section in the os.path.join function to be orders, assuming it would call the data frame, but that did not work so I had to switch it to my current working directory.

### Part 8 — prove the fixes

Assertions are how you state what must be true. If one fails, the notebook stops and tells you which claim broke — much better than scrolling for a wrong number.

**TODO:** uncomment each line and make them all pass.

In [22]:
assert isinstance(greeting, str) and greeting != ''
assert total == 30
assert items[-1] == 'hat'
assert average == 5
assert len(df) == 2
assert len(orders) >= 2
print('All checks passed.')

All checks passed.

### Part 9 — the submit drill

This is the part that is actually being graded on process. Do it in order.

1. **Restart the kernel and Run All.** Zero errors, top to bottom.
2. Download the notebook and put it in your repo under `notebooks/01-foundations/`, named `2026-09-04 — Submission Drill and Fix a Broken Notebook — Lab.ipynb`.
3. Commit with a message that says what you did, then push.
4. Confirm on github.com that the file is there and opens.
5. Fill in the cell below and submit both links in Canvas.

**TODO:** fill in the four values and make the check pass.

In [29]:
from numpy import true_divide
import re

repo_url = 'https://github.com/TommySnyd/ds2002-fa26'
commit_sha = '51558a8'
notebook_link = 'https://colab.research.google.com/github/TommySnyd/ds2002-fa26/blob/main/notebooks/01-foundations/2026-09-04%20%E2%80%94%20Submission%20Drill%20and%20Fix%20a%20Broken%20Notebook%20%E2%80%94%20Lab.ipynb#scrollTo=85yEH14PVu9V$0'
ran_restart_and_run_all = True   # TODO: set True after you actually do it - done

checks = {
    'repo URL is a github.com URL':
        repo_url.startswith('https://github.com/')
        and repo_url.count('/') >= 4,
    'commit hash looks like a hash':
        bool(re.fullmatch(r'[0-9a-f]{7,40}', commit_sha.strip())),
    'notebook link filled in':
        notebook_link.startswith('http'),
    'restarted and ran all':
        ran_restart_and_run_all is True,
}

for label, passed in checks.items():
    print('PASS' if passed else 'FAIL', '-', label)

print()
print('Ready to submit:', all(checks.values()))

PASS - repo URL is a github.com URL
PASS - commit hash looks like a hash
PASS - notebook link filled in
PASS - restarted and ran all

Ready to submit: True

### Write-up

Bugs 4 and 6 did not raise an error. In a few sentences: how would you catch that class of bug in a project where you do not already know the right answer? Name something concrete you could add to a notebook.

This is a hard one. On projects in the past I have run into these issues and usually have not realized until the end of the project when I check the final outputs and notice they are out. When it comes to calculations, I believe it is best to also do them by hand so that you can know what answers you should have gotten. Also having AI review the code on past projects has become a very useful tool.

### Stretch

Write a `check_orders(df)` function that raises a clear error if the frame is missing either expected column, has zero rows, or contains a negative value in `units`. Then call it on `orders`. This is the shape of validation you will want in both projects.

In [28]:
COLUMNS=['game', 'units']


def check_orders(df, columns_exp=COLUMNS):
  col_missing = [c for c in columns_exp if c not in df.columns]
  if col_missing:
    raise ValueError(f"orders is missing the following column(s), {col_missing}")
  if len(df) == 0:
    raise ValueError(f"orders has 0 rows, please fix")
  if (df['units'] < 0).any():
    raise ValueError(f"Negative valiue in the units, review")
  return df
check_orders(orders)




# stretch

         game  units
0    NC State   1450
1  Louisville   1610